version: '3.8'
services:
  client:
    stdin_open: true
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src 
    ports:
      - "3000:3000"      
    depends_on:
      - server
    networks:
      - mern-net
    container_name: client-con  
  
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    volumes:
      - ./Server:/app  #chnges in codepart wil autmticly reeflect in cont. hence 
                       #server wll restart
    ports:
      - "5000:5000"     #localHost:containerHost
    depends_on:
      - mongodb
    networks:
      - mern-net
    container_name: server-con

  mongodb:
    image: mongo:6.0.5
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-net
    container_name: mongo-con

volumes:               #leave them empty, default config
  mongodbdata:

networks:
  mern-net:
    driver: bridge