apiVersion: apps/v1
kind: Statefulset
metadata:
  name: mongodb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        name: db-pod
  template:            # info. related to pod under template
    metadata:
       labels:
        name: db-pod
    spec:
      containers:
       - name: db-con
         image: mongo
         ports:
            - containerPort: 27017
         volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /var/lib/mongo
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi