apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        name: server-pod
  template:            # info. related to pod wll b under template
    metadata:
       labels:
        name: server-pod
    spec:
      containers:
       - name: server-con
         image: node:latest
         ports: 
            - containerPort: 5000
         env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REACT_APP_BACKEND_URL  )
